# Site settings
title: Dash
email: carly.strasser@ucop.edu
description: "Information about the Dash project"
baseurl: "http://CDLUC3.github.io/dash"
url: "http://dash.ucop.edu"
twitter_username: carlystrasser
github_username:  strasser

# Build settings
markdown: kramdown
permalink: pretty
