# Site settings
title: Dash
email: carly.strasser@ucop.edu
description: "Information about the Dash project"
baseurl: "http://strasser.github.io/dash"
url: "http://dash.ucop.edu"
twitter_username: UC3CDL
github_username:  CDLUC3

# Build settings
markdown: kramdown
permalink: pretty
